---
title: "Fit Multiple OU Models to Discrete Mapping Data using OUwie (Depth Preference)"
author: "Callum Bucklow"
date: "`r Sys.Date()`"
output: html_document
---

```{r Setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE) ##Remove messages for all chunks
knitr::opts_chunk$set(warning = FALSE) ##Remove warnings for all chunks
```

```{r Libraries}
# Load the necessary libraries
library(tidyverse) #data wrangling
library(tidyr) #data wrangling
library(dplyr)
library(ggplot2) #for plotting when I don't want to use Base R
library(gridExtra) #for ggplot, to plot multiple plots together
library(fitdistrplus) #for fitting distributions to data
library(ape) #for phylogeny manipulation and all the rest
library(phytools) #for various things, including phylogenetic PCA, PGLM etc.
library(nlme) #for pgls
library(geiger) #for fitting trait evolution models to phylogenies
library(OUwie) #for fitting multiple regime OU models to trait evolution models
library(caper) #for pgls and will report pseudo-r2 for these models
```

# Fitting Multiple OU Models to Depth Preference Simmap

```{r Import Depth Preference Simmap}

all_species_depth_simmap <- readRDS("Data/all_species_depth_simmap.rds")

```

```{r Prepare All Species Data with their Depth Preference}
#remember we are using the tree that has been pruned to those for which we know whether they are piscivorous or not

#import qualitative data
all_species_stored_data_piscivore <-
  read.csv('Data/all_species_stored_data_piscivore.csv')

#import quant data
all_species_matrix_data_piscivore <-  read.csv('Data/all_species_matrix_data_piscivore.csv')

#import piscivore pruned tree:
all_species_tree_piscivore_pruned <- read.tree('Data/all_species_tree_piscivore_pruned.txt')

#save edge lengths
all_species_tree_depth_pruned_edges <- all_species_tree_piscivore_pruned$edge.length

#create trait variable for fitting discrete models:
all_species_depth <- all_species_stored_data_piscivore$depth
names(all_species_depth) <- all_species_stored_data_piscivore$species_name

#convert matrix into dataframe
all_species_matrix_data_df <- as.data.frame(all_species_matrix_data_piscivore)

#isolate quantitative data
all_species_depth_matrix <- 
  all_species_matrix_data_df %>%
  filter(names(all_species_depth) %in% all_species_matrix_data_df$X)
```

```{r Define Function to Fit Multiple Models (OUwie) to Depth Preference Simmap}
fit_multiple_regime_models <- function(tree, species_data, matrix_data, simmap_tree_index = 1, fit_common_models = TRUE) {
  #Isolate depth data
  species_depth_null <- species_data
  names(species_depth_null) <- NULL
  
  #create the OUwie dataframe
  ouwie_df <- data.frame(
    species_name = names(species_data),
    variable = species_depth_null,
    tc = as.numeric(matrix_data[, 4])
  )
  
  #initialize a list to store model fits
  fits <- list()
  aic_values <- c()
  
  if (simmap_tree_index == random_tree_indices[[1]] && fit_common_models) {
    # Fit common models only for the first tree
    fits$BM1 <- OUwie(tree[[simmap_tree_index]], ouwie_df, model = 'BM1', simmap.tree = TRUE)
    fits$OU1 <- OUwie(tree[[simmap_tree_index]], ouwie_df, model = 'OU1', simmap.tree = TRUE, root.station = FALSE)
    
    aic_values <- c(
      BM1 = fits$BM1$AIC,
      OU1 = fits$OU1$AIC
    )
  } else {
    # Use the results from the first tree for subsequent trees
    fits$BM1 <- NULL  # Placeholder for consistency
    fits$OU1 <- NULL  # Placeholder for consistency
    
    # Reuse AIC values from the first tree
    aic_values <- c(
      BM1 = NA,  # Indicating that the value is reused
      OU1 = NA   # Indicating that the value is reused
    )
  }
  
  # Fit models specific to each tree
  fits$BMS <- OUwie(tree[[simmap_tree_index]], ouwie_df, model = 'BMS', simmap.tree = TRUE, root.station = FALSE)
  fits$OUM <- OUwie(tree[[simmap_tree_index]], ouwie_df, model = 'OUM', simmap.tree = TRUE, root.station = FALSE)
  fits$OUMV <- OUwie(tree[[simmap_tree_index]], ouwie_df, model = 'OUMV', simmap.tree = TRUE, root.station = FALSE)
  fits$OUMA <- OUwie(tree[[simmap_tree_index]], ouwie_df, model = 'OUMA', simmap.tree = TRUE, root.station = FALSE)
  fits$OUMVA <- OUwie(tree[[simmap_tree_index]], ouwie_df, model = 'OUMVA', simmap.tree = TRUE, root.station = FALSE)
  
  # Append the AIC values of the tree-specific models
  aic_values <- c(
    aic_values,
    BMS = fits$BMS$AIC,
    OUM = fits$OUM$AIC,
    OUMV = fits$OUMV$AIC,
    OUMA = fits$OUMA$AIC,
    OUMVA = fits$OUMVA$AIC
  )
  
  # Create a list to store all model fits and AIC values
  result <- list(
    aic_values = aic_values,
    fits = fits
  )
  
  return(result)
}

```

```{r Fit Multiple OU Models to Data using OUwie for Depth Preference}

# Fit the models for 100 randomly chosen trees
set.seed(1931) # Setting a seed for reproducibility
random_tree_indices <- sample(length(all_species_depth_simmap), 100)

#generate random tree index
#for (i in random_tree_indices) {
  #all_species_depth_simmap[[i]]$edge.length <- all_species_tree_depth_pruned_edges
#}

#initialise empty list to store results
#ouwie_all_results_depth <- list()

#for (i in random_tree_indices) {
  #cat("Fitting models for tree index:", i, "\n")
  #results <- fit_multiple_regime_models(
    #tree = all_species_depth_simmap,
    #species_data = all_species_depth,
    #matrix_data = all_species_matrix_data_df,
    #simmap_tree_index = i,
    #fit_common_models = TRUE #fits BM1 and OU1 models to first tree only (since it will be the same regardless of tree)
  #)
  #ouwie_all_results_depth[[i]] <- results
#}

#save the results output to prevent having to redo analysis:
#saveRDS(ouwie_all_results_depth, "Data/ouwie_all_results_depth.rds")
```

```{r Filtering and Assembling OUwie Water System Results}

#import the RDS object with the OU results:
ouwie_all_results_depth <- readRDS("Data/ouwie_all_results_depth.rds")

#filter results output to only contain the trees for which models were fitted:
ouwie_all_results_depth_filtered <- ouwie_all_results_depth[random_tree_indices]

#save filtered data
saveRDS(ouwie_all_results_depth_filtered, 'Data/ouwie_all_results_depth_filtered.rds')

# Initialize an empty list to store AIC values
ouwie_all_results_depth_filtered_aic <- list()

# Loop through each model result and extract the AIC values
for (i in seq_along(ouwie_all_results_depth_filtered)) {
  ouwie_all_results_depth_filtered_aic[[i]] <- ouwie_all_results_depth_filtered[[i]]$aic_values
}

# Combine the list into a matrix 
ouwie_all_results_depth_filtered_aic_df <- do.call(rbind, ouwie_all_results_depth_filtered_aic)

#convert matrix to dataframe:
ouwie_all_results_depth_filtered_aic_df <- as.data.frame(ouwie_all_results_depth_filtered_aic_df)

#convert into long format for easier plotting:
ouwie_all_results_depth_filtered_aic_df_long <- ouwie_all_results_depth_filtered_aic_df %>%
  pivot_longer(cols = everything(), 
               names_to = "model", 
               values_to = "aic")
```


```{r Plotting AIC Values for Each Model Fit}

#plot the aic values for each of the models (note that BM and OU1 will be the same for each model)
a1 <- ggplot(ouwie_all_results_depth_filtered_aic_df_long, aes(x=model, y=aic))+
      geom_boxplot()+
      theme_classic()
a1
ggsave("Figures/OUwie Results/ouwie_all_results_depth_aic_full.jpeg", 
       plot = a1, dpi=300, width = 12, height = 10, units = 'cm')

#alter y axis to esmphasise better fitting models
a1a <- ggplot(ouwie_all_results_depth_filtered_aic_df_long, aes(x=model, y=aic))+
      geom_boxplot(outlier.shape = NA)+
      ylim(-1400, -1300)+
      theme_classic()
a1a
ggsave("Figures/OUwie Results/ouwie_all_results_depth_aic_short.jpeg", 
       plot = a1a, dpi=300, width = 12, height = 10, units = 'cm')

#isolate the OUMVA aic values
aic_oumva <- 
  ouwie_all_results_depth_filtered_aic_df_long %>%
  filter(model == "OUMVA")

#calculate the number of runs in which the AIC is 'reasonable' (relative to the other model fits)
aic_oumva_less_than <- sum(aic_oumva$aic < -2000)
aic_oumva_less_than

#alter y axis to emphasise better fitting models
a1b <- ggplot(ouwie_all_results_depth_filtered_aic_df_long, aes(x=model, y=aic))+
      geom_boxplot(outlier.shape = NA)+
      ylim(-1370, -1350)+
      theme_classic()
a1b
ggsave("Figures/OUwie Results/ouwie_all_results_depth_aic_short.jpeg", 
       plot = a1b, dpi=300, width = 12, height = 10, units = 'cm')

```

```{r Extract Parameter Values from OUM Model}
#initialize an empty list to store the filtered sigma^2 and root node values
ouwie_all_results_depth_OUM_parameters <- list()

#loop through each model result and filter by AICc
for (i in seq_along(ouwie_all_results_depth_filtered)) {
  # Extract the AICc value for the OUMV model
  aicc_value <- ouwie_all_results_depth_filtered[[i]]$fits$OUM$AICc
  
  # Check if AICc is greater than or equal to -2000
  if (aicc_value >= -2000) {
    #define the regime
    regime <- c("bathydemersal", "benthopelagic", "demersal", "pelagic")
    
    #extract alpha value
    alpha <- ouwie_all_results_depth_filtered[[i]]$fits$OUM$solution[1,]
    
    #extract the sigma^2 value (second row of the solution matrix)
    sigma_squared <- ouwie_all_results_depth_filtered[[i]]$fits$OUM$solution[2,]
    
    #extract the theta value and its standard error (first row of the theta matrix)
    theta <- ouwie_all_results_depth_filtered[[i]]$fits$OUM$theta 
    
    #combine into a named dataframe and add to the result list
    ouwie_all_results_depth_OUM_parameters[[i]] <- data.frame(
      regime = regime,
      alpha = alpha,
      sigma_squared = sigma_squared,
      theta = theta[1:4],
      theta_se = theta[,2],
      half_life = log(2)/alpha
    )
  }
}

# Remove any NULL elements from the result list (if some models were excluded)
ouwie_all_results_depth_OUM_parameters <- ouwie_all_results_depth_OUM_parameters[!sapply(ouwie_all_results_depth_OUM_parameters, is.null)]

# Combine the list into a single dataframe
ouwie_all_results_depth_OUM_parameters_df <- do.call(rbind, ouwie_all_results_depth_OUM_parameters)

# Convert matrix to dataframe (if needed, but do.call(rbind, ...) already returns a dataframe)
ouwie_all_results_depth_OUM_parameters_df <- as.data.frame(ouwie_all_results_depth_OUM_parameters_df)

#remove bathydemersal
ouwie_all_results_depth_OUM_parameters_df <-
  ouwie_all_results_depth_OUM_parameters_df %>%
  filter(regime != 'bathydemersal')

#calculate mu (directional trend coefficient)
ouwie_all_results_depth_OUM_parameters_df$mu <-
  ouwie_all_results_depth_OUM_parameters_df$theta * ouwie_all_results_depth_OUM_parameters_df$alpha

#output table to check 
ouwie_all_results_depth_OUM_parameters_df
```

```{r}
#plot the theta/optima values:
a6 <- ggplot(ouwie_all_results_depth_OUM_parameters_df, aes(x=regime, y=mu))+
      geom_boxplot()+
      geom_jitter()+
      ylab(expression("Directional Trend Coefficient (" * mu * ")"))+
      xlab("Depth Preference")+
      theme_classic()
a6
```
```{r Summary of OUM Parameters}
#calculate summary of parameter values
summary_OUM_parameters <- 
  ouwie_all_results_depth_OUM_parameters_df %>%
  group_by(regime) %>%
  summarise(median_sigma_squared = median(sigma_squared),
            min_sigma_squared = min(sigma_squared),
            max_sigma_squared = max(sigma_squared),
            median_half_life = median(half_life),
            median_alpha = median(alpha),
            min_alpha = min(alpha),
            max_alpha = max(alpha),
            min_half_life = min(half_life),
            max_half_life = max(half_life),
            median_theta = median(theta),
            min_theta = min(theta),
            max_theta = max(theta),
            median_se = median(theta_se),
            min_se = min(theta_se),
            max_se = max(theta_se),
            median_mu = median(mu),
            min_mu = min(mu),
            max_mu = max(mu))

summary_OUM_parameters

write.csv(summary_OUM_parameters, '~/Desktop/depth_OUM_paramters.csv')
```

```{r Extract Parameter Values from OUMV Model}
#initialize an empty list to store the filtered sigma^2 and root node values
ouwie_all_results_depth_OUMV_parameters <- list()

#loop through each model result and filter by AICc
for (i in seq_along(ouwie_all_results_depth_filtered)) {
  #extract the AICc value for the OUMVV model
  aicc_value <- ouwie_all_results_depth_filtered[[i]]$fits$OUMV$AICc
  
  #check if AICc is greater than or equal to -2000
  if (aicc_value >= -2000) {
    #define the regime
    regime <- c("bathydemersal", "benthopelagic", "demersal", "pelagic")
    
    #extract alpha value
    alpha <- ouwie_all_results_depth_filtered[[i]]$fits$OUMV$solution[1,]
    
    #extract the sigma^2 value (second row of the solution matrix)
    sigma_squared <- ouwie_all_results_depth_filtered[[i]]$fits$OUMV$solution[2,]
    
    #extract the theta value and its standard error (first row of the theta matrix)
    theta <- ouwie_all_results_depth_filtered[[i]]$fits$OUMV$theta 
    
    #combine into a named dataframe and add to the result list
    ouwie_all_results_depth_OUMV_parameters[[i]] <- data.frame(
      regime = regime,
      alpha = alpha,
      sigma_squared = sigma_squared,
      theta = theta[1:4],
      theta_se = theta[,2],
      half_life = log(2)/alpha
    )
  }
}

#remove any NULL elements from the result list (if some models were excluded)
ouwie_all_results_depth_OUMV_parameters <- ouwie_all_results_depth_OUMV_parameters[!sapply(ouwie_all_results_depth_OUMV_parameters, is.null)]

#combine the list into a single dataframe
ouwie_all_results_depth_OUMV_parameters_df <- do.call(rbind, ouwie_all_results_depth_OUMV_parameters)

#convert matrix to dataframe
ouwie_all_results_depth_OUMV_parameters_df <- as.data.frame(ouwie_all_results_depth_OUMV_parameters_df)

#output table to check 
ouwie_all_results_depth_OUMV_parameters_df

#remove bathydemersal
ouwie_all_results_depth_OUMV_parameters_df <-
  ouwie_all_results_depth_OUMV_parameters_df %>%
  filter(regime != 'bathydemersal')

#calculate mu (directional trend coefficient)
ouwie_all_results_depth_OUMV_parameters_df$mu <-
  ouwie_all_results_depth_OUMV_parameters_df$theta * ouwie_all_results_depth_OUMV_parameters_df$alpha
```


```{r Plot the Theta Values by Depth Preference}
#plot the theta/optima values:
a4 <- ggplot(ouwie_all_results_depth_OUMV_parameters_df, aes(x=regime, y=theta))+
      geom_boxplot()+
      geom_jitter()+
      ylab(expression("Trait Optima (" * theta * ")"))+
      xlab("Depth Preference")+
      theme_classic()
a4

ggsave("Figures/OUwie Results/depth_preference_OUMV_theta_no_bathydemersal.jpeg", 
       plot = a4, dpi=300, width = 12, height = 10, units = 'cm')

#'Directional Trend Coefficient' μ
```

```{r Kruskal Test and Wilcox Test to Check for Sig Differences in Theta}
#test for sig. dif. in median between groups
kruskal.test(theta ~ depth, data=ouwie_all_results_depth_OUMV_optima_df_no_bathydemersal)

#pairwise comparison as three categories (benthopelagic, demersal and pelagic)
pairwise.wilcox.test(ouwie_all_results_depth_OUMV_optima_df_no_bathydemersal$theta,
                     ouwie_all_results_depth_OUMV_optima_df_no_bathydemersal$depth, p.adjust.method = "bonferroni")

```

```{r}
#plot the theta/optima values:
a5 <- ggplot(ouwie_all_results_depth_OUMV_parameters_df, aes(x=regime, y=mu))+
      geom_boxplot()+
      geom_jitter()+
      ylab(expression("Directional Trend Coefficient (" * mu * ")"))+
      xlab("Depth Preference")+
      theme_classic()
a5
```


```{r Summary of OUMV Parameters}
#calculate summary of parameter values
summary_OUMV_parameters <- 
  ouwie_all_results_depth_OUMV_parameters_df %>%
  group_by(regime) %>%
  summarise(median_sigma_squared = median(sigma_squared),
            min_sigma_squared = min(sigma_squared),
            max_sigma_squared = max(sigma_squared),
            median_half_life = median(half_life),
            median_alpha = median(alpha),
            min_alpha = min(alpha),
            max_alpha = max(alpha),
            min_half_life = min(half_life),
            max_half_life = max(half_life),
            median_theta = median(theta),
            min_theta = min(theta),
            max_theta = max(theta),
            median_se = median(theta_se),
            min_se = min(theta_se),
            max_se = max(theta_se),
            median_mu = median(mu),
            min_mu = min(mu),
            max_mu = max(mu))

summary_OUMV_parameters

write.csv(summary_OUMV_parameters, '~/Desktop/depth_OUMV_paramters.csv')
```






